### ISSUE TITLE
OffVis 1.2 missing file

### ISSUE THREAD

**Issue by otofoto** [arizvisa/windows-binary-tools#1]
Cases.dll is missing from windows-binary-tools/offvis/Vis/

**Comment by arizvisa** [comment]
Do you have a link to the original OffVis v1.2 archive? I looked around, but I could only find v1.1 at http://go.microsoft.com/fwlink/?LinkId=15879. I don't remember where I got that original .zip file, heh.

**Comment by otofoto** [comment]
just use cases.dll from 1.1 version. Without cases.dll file it doesn't show parsers.
Your repository is only place I have found this OffVis 1.2.3625.22702 version.

**Comment by arizvisa** [comment]
Ah, the reason why it doesn't show the parsers is because you need to specify the path to `/Patterns` via the options. When you run it, go to `Tools`, then `Options`, and then specify the path.

You can tell that Cases.dll isn't needed by grepping for that string through those binaries. Microsoft moved the parsers into "Detection Logic" now.

**Comment by arizvisa** [comment]
Let me know if that gets it to list the parsers for you.

**Comment by otofoto** [comment]
This worked.

Interesting that 1.1 changelog also mention that there is added a “Reallocate” feature (under Tools menu) that makes some corrupted files parse-able. But it seems that function actually is called defragment.

**Comment by arizvisa** [comment]
This is OT, but if you need to modify details related to Office documents. I have some other tools for python2 that might be better than offvis that could be useful. The only thing you need to do extra is extract the streams individually, which you can do with the tools at https://github.com/arizvisa/compdoc-tools. After that, the https://github.com/arizvisa/syringe repo contains the two components that are key.

First there's ptypes, and then there's the parser templates at https://github.com/arizvisa/syringe/tree/master/template/office which can be used to get details about records in said document. This way if you need to modify the records in the stream for testing/breaking something you can do it programmatically a lot easier.

Something like the following will load the file into your python interpreter.
```
sys.path.append('/path/to/syringe/lib')
sys.path.append('/path/to/syringe/template')
import ptypes,office.excel # or office.powerpoint
ptypes.setsource(ptypes.provider.file('/path/to/whatever/stream', mode='rw'))
z=office.excel.File()      # or office.powerpoint.File()
z=z.l
```

Then you could do `z.at(offset)` to dump the structure at a given offset, `z[x]` to select a specific worksheet or slide. `a = z[x]; rec = a[5]` to select a specific record, `rec.p` to go up a record, etc.. To write stuff, just select your field and call `.set` on it like `rec['Header']['Size'].set(57005)`. After setting your fields, just use `rec.commit()` or `z.commit()` to write them back to the file.

**Comment by arizvisa** [comment]
Anywayz, closing this issue as it's been resolved.
